language: csharp
solution: Sudoku.sln

dist: xenial
mono: latest

install:
  - nuget restore Sudoku.sln
  - nuget install NUnit.Console -Version 3.9.0 -OutputDirectory testrunner

script:
  - msbuild /p:Configuration=Debug Sudoku.sln
  - mono testrunner/NUnit.ConsoleRunner.3.9.0/tools/nunit3-console.exe Sudoku.Test/bin/Debug/Sudoku.Test.dll
